"""Lens-specific note extractor for the general-zettelkasten lens.

Parallel to `tools/incident_extractor.py` for the engineering-alexander
lens. Architecture contract:

1. **No LLM calls.** This module does deterministic IO + frontmatter +
   path resolution only. Claude (the invoking session) does all content
   authoring via `.agent/lenses/general-zettelkasten/SKILL.md` and the
   examples in `examples.md`. The stub body is a structured TODO template
   showing Claude where to put each progressive-summary layer.

2. **Pure-function core, filesystem shell.** `run_note_extractor` does all
   I/O. Slug derivation and stub rendering are pure helpers, independently
   testable.

3. **Force flag.** Matches `incident_extractor` semantics: if the output
   file exists with user content (no AGENT_MARKER), return
   `(None, "exists-user-content")` when force=False; overwrite when
   force=True. Agent stubs (marker present) are silently overwritten on
   force only.

4. **Kind inference.** URL → "article"; PDF → "paper"; markdown / text →
   "other". Users can edit the frontmatter kind after ingest.

Output path follows `lens.entity_model.tier_0` ("note") via:
    vault / "wiki" / "note" / f"{slug}.md"

Frontmatter fields written (zettelkasten-specific):
    slug, kind, source_url | source_path, lens, bloom, concepts,
    layer_1_bolds, layer_2_fragments, layer_3_thesis, ingested_at,
    input_type, status

All content fields are null / [] — filled by Claude content authoring.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

try:
    from lens_loader import LensConfig  # type: ignore[no-redef]
except ImportError:  # tools/ also importable as a package
    from tools.lens_loader import LensConfig

LENS_ID = "general-zettelkasten"
AGENT_MARKER = "<!-- ingest-runner:agent-stub -->"
"""Re-exported so test fixtures can import from one place."""

# ---------------------------------------------------------------------------
# Kind inference
# ---------------------------------------------------------------------------

_KIND_MAP: dict[str, str] = {
    "url": "article",
    "pdf": "paper",
    "markdown": "other",
    "text": "other",
}


def _infer_kind(input_type: str) -> str:
    """Map input_type to a zettelkasten note kind."""
    return _KIND_MAP.get(input_type, "other")


# ---------------------------------------------------------------------------
# Slug derivation — mirrors incident_extractor._slug_from_input exactly
# ---------------------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug_from_input(raw: str) -> str:
    """Derive a deterministic kebab-case slug.

    URL: domain + path → kebab.
    File: stem → kebab.
    """
    if raw.startswith(("http://", "https://")):
        parsed = urlparse(raw)
        base = (parsed.netloc + parsed.path).strip("/")
    else:
        base = Path(raw).stem
    lower = base.lower()
    clean = _SLUG_RE.sub("-", lower).strip("-")
    return clean or "untitled"


# ---------------------------------------------------------------------------
# Stub rendering
# ---------------------------------------------------------------------------


def _render_note_stub(
    slug: str,
    kind: str,
    raw: str,
    input_type: str,
    lens: LensConfig,
) -> str:
    """Render the frontmatter + structured TODO body.

    The body shows Claude exactly where to place each progressive-summary
    layer, the Bloom tag, concept atoms, and back-references. The shape
    matches the worked examples in `examples.md` so Claude's content
    authoring is calibrated to the right structure immediately.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "---",
        f"type: note",
        f"lens: {lens.id}",
        f"slug: {slug}",
        f"kind: {kind}",
        f"ingested_at: {now}",
        f"input_type: {input_type}",
    ]
    if raw.startswith(("http://", "https://")):
        lines.append(f"source_url: {raw}")
    else:
        lines.append(f"source_path: {raw}")

    # Content fields — null / [] until Claude fills them in.
    lines.extend([
        "bloom: null",
        "concepts: []",
        "layer_1_bolds: []",
        "layer_2_fragments: []",
        "layer_3_thesis: null",
        "status: draft",
        "---",
        "",
        AGENT_MARKER,
        "",
        f"# {slug}",
        "",
        f"_Stub generated by `/ingest` under lens `{lens.id}`._",
        "_Fill each section below per `.agent/lenses/general-zettelkasten/prompts.md`._",
        "",
        "## Layer 1 — bold key sentences",
        "",
        "<!-- Bold verbatim sentences from the source that carry the highest",
        "     conceptual weight. Never paraphrase in Layer 1. -->",
        "",
        "- TODO",
        "",
        "## Layer 2 — bold fragments",
        "",
        "<!-- 3–5 conceptual fragments (not 'interesting phrases').",
        "     Each fragment must anchor at least one downstream concept-atom. -->",
        "",
        "- TODO",
        "",
        "## Layer 3 — one-sentence thesis",
        "",
        "<!-- Your synthesis, not the author's thesis. One sentence, no hedges.",
        "     If you need two sentences the note is not atomic yet. -->",
        "",
        "TODO",
        "",
        "## Concepts (tier_1_atoms)",
        "",
        "<!-- Propose concept wikilinks that appear in ≥2 notes.",
        "     Format: `[[concept-slug]]` — explanation of why it earns its place. -->",
        "",
        "- TODO",
        "",
        "## Back-references",
        "",
        "<!-- Each back-ref must include a specific claim about HOW the other",
        "     note shifts interpretation of this one — not just 'related to X'. -->",
        "",
        "- TODO",
        "",
        "## Source",
        f"- Input: `{raw}`",
        f"- Type: {input_type}",
        f"- Kind: {kind}",
        "",
        f"<!-- Bloom level choices: remember / understand / apply / analyze / evaluate / create -->",
        f"<!-- See `.agent/lenses/{lens.id}/examples.md` for worked examples. -->",
        "",
    ])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run_note_extractor(
    vault: Path,
    lens: LensConfig,
    raw: str,
    input_type: str,
    force: bool = False,
) -> tuple[Path | None, str | None]:
    """Write a populated tier_0 note stub for the general-zettelkasten lens.

    Parameters
    ----------
    vault:
        Root of the Bab-ilu vault (resolved absolute path).
    lens:
        Must have `lens.id == LENS_ID` and `lens.entity_model["tier_0"] == "note"`.
    raw:
        Original input string (URL, file path, or plain text identifier).
    input_type:
        One of "url" | "pdf" | "markdown" | "text".
    force:
        When True, overwrite even user-authored content.

    Returns
    -------
    (output_path, None)   on success — file written.
    (None, error_msg)     on failure — nothing written.
    """
    # Validate lens.
    if lens.id != LENS_ID:
        return None, (
            f"note_extractor only handles {LENS_ID!r}, got {lens.id!r}"
        )

    # Validate vault exists.
    if not vault.exists():
        return None, f"vault path does not exist: {vault}"

    # Derive output path.
    tier_0 = lens.entity_model.get("tier_0", "note")
    slug = _slug_from_input(raw)
    output_path = vault / "wiki" / tier_0 / f"{slug}.md"

    # Collision guard.
    if output_path.exists() and not force:
        existing = output_path.read_text(encoding="utf-8")
        if AGENT_MARKER not in existing:
            return None, "exists-user-content"
        # Agent stub exists + force=False → skip silently (let caller fall
        # through to stub writer, matching incident_extractor behaviour).
        return None, None

    # Render and write.
    kind = _infer_kind(input_type)
    body = _render_note_stub(slug, kind, raw, input_type, lens)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(body, encoding="utf-8")
    return output_path, None
